# Generated by database migrator
import peewee


def migrate(migrator, database, **kwargs):
    migrator.add_columns("servers", ignored_exits=peewee.CharField(default="0"))
    """
    Write your migrations here.
    """


def rollback(migrator, database, **kwargs):
    migrator.drop_columns("servers", ["ignored_exits"])
    """
    Write your rollback migrations here.
    """
