# Generated by database migrator
import peewee


def migrate(migrator, database, **kwargs):
    migrator.add_columns("servers", created_by=peewee.IntegerField(default=-100))
    """
    Write your migrations here.
    """


def rollback(migrator, database, **kwargs):
    migrator.drop_columns("servers", ["created_by"])
    """
    Write your rollback migrations here.
    """
