# Generated by database migrator
import peewee


def migrate(migrator, database, **kwargs):
    migrator.add_columns(
        "users",
        pfp=peewee.CharField(default="/static/assets/images/faces-clipart/pic-3.png"),
    )
    """
    Write your migrations here.
    """


def rollback(migrator, database, **kwargs):
    migrator.drop_columns("users", ["pfp"])
    """
    Write your rollback migrations here.
    """
