# Generated by database migrator
import peewee


def migrate(migrator, database, **kwargs):
    migrator.add_columns("servers", shutdown_timeout=peewee.IntegerField(default=60))
    """
    Write your migrations here.
    """


def rollback(migrator, database, **kwargs):
    migrator.drop_columns("servers", ["shutdown_timeout"])
    """
    Write your rollback migrations here.
    """
