# Generated by database migrator
import peewee


def migrate(migrator, database, **kwargs):
    migrator.add_columns(
        "crafty_settings", login_photo=peewee.CharField(default="login_1.jpg")
    )
    """
    Write your migrations here.
    """


def rollback(migrator, database, **kwargs):
    migrator.drop_columns("crafty_settings", ["login_photo"])
    """
    Write your rollback migrations here.
    """
