# Generated by database migrator
import peewee


def migrate(migrator, database, **kwargs):
    migrator.add_columns("schedules", next_run=peewee.CharField(default=""))
    """
    Write your migrations here.
    """


def rollback(migrator, database, **kwargs):
    migrator.drop_columns("schedules", ["next_run"])
    """
    Write your rollback migrations here.
    """
