# Generated by database migrator
import peewee


def migrate(migrator, database, **kwargs):
    migrator.add_columns("users", manager=peewee.IntegerField(null=True))
    """
    Write your migrations here.
    """


def rollback(migrator, database, **kwargs):
    migrator.drop_columns("users", ["manager"])
    """
    Write your rollback migrations here.
    """
