# Generated by database migrator
import peewee


def migrate(migrator, database, **kwargs):
    migrator.rename_column("schedules", "comment", "name")

    """
    Write your migrations here.
    """


def rollback(migrator, database, **kwargs):
    migrator.rename_column("schedules", "name", "comment")
    """
    Write your rollback migrations here.
    """
