# Generated by database migrator
import peewee


def migrate(migrator, database, **kwargs):
    migrator.add_columns(
        "crafty_settings", master_server_dir=peewee.CharField(default="")
    )
    """
    Write your migrations here.
    """


def rollback(migrator, database, **kwargs):
    migrator.drop_columns("crafty_settings", ["master_server_dir"])
    """
    Write your rollback migrations here.
    """
