# Generated by database migrator
import peewee


def migrate(migrator, database, **kwargs):
    migrator.add_columns(
        "crafty_settings", login_opacity=peewee.IntegerField(default=100)
    )
    """
    Write your migrations here.
    """


def rollback(migrator, database, **kwargs):
    migrator.drop_columns("crafty_settings", ["login_opacity"])
    """
    Write your rollback migrations here.
    """
